-- ========================================
-- AI Fashion Photo Generator - Complete Supabase Setup
-- ========================================
-- Copy this file into Supabase SQL Editor and RUN it
-- Includes ALL features: basic app, admin dashboard, and user custom content
-- ========================================

-- Step 1: Drop old tables if they exist (for clean start)
DROP TABLE IF EXISTS generations CASCADE;
DROP TABLE IF EXISTS generated_images CASCADE;
DROP TABLE IF EXISTS admin_activity_logs CASCADE;
DROP TABLE IF EXISTS user_limits CASCADE;
DROP TABLE IF EXISTS content_library CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;

-- ========================================
-- Part 1: Main Application Tables
-- ========================================

-- 1.1: Generated Images Table
CREATE TABLE generated_images (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  garment_path TEXT NOT NULL,
  model_id TEXT,
  background_id TEXT,
  pose_id TEXT,
  camera_angle_id TEXT,
  style_id TEXT,
  lighting_id TEXT,
  prompt TEXT,
  description TEXT,
  generated_image_url TEXT NOT NULL,
  instagram_caption TEXT,
  user_email TEXT,
  is_premium_generation BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add comments
COMMENT ON TABLE generated_images IS 'Store AI-generated images';
COMMENT ON COLUMN generated_images.garment_path IS 'Garment image path (can be JSON array for multiple garments)';
COMMENT ON COLUMN generated_images.instagram_caption IS 'Instagram caption generated by Gemini AI';
COMMENT ON COLUMN generated_images.pose_id IS 'Body pose ID (standing, sitting, etc.)';
COMMENT ON COLUMN generated_images.camera_angle_id IS 'Camera angle ID';
COMMENT ON COLUMN generated_images.style_id IS 'Photo style ID';
COMMENT ON COLUMN generated_images.lighting_id IS 'Lighting ID';

-- 1.2: Create Indexes for generated_images
CREATE INDEX idx_generated_images_user_id ON generated_images(user_id);
CREATE INDEX idx_generated_images_created_at ON generated_images(created_at DESC);
CREATE INDEX idx_generated_images_model_id ON generated_images(model_id);
CREATE INDEX idx_generated_images_background_id ON generated_images(background_id);
CREATE INDEX idx_generated_images_user_email ON generated_images(user_email);

-- ========================================
-- Part 2: Admin Dashboard Tables
-- ========================================

-- 2.1: Admin Users Table
CREATE TABLE admin_users (
  id BIGSERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'admin' CHECK (role IN ('admin', 'super_admin')),
  is_active BOOLEAN DEFAULT true,
  last_login TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Default admin: email = admin@example.com, password = admin123
-- ⚠️ CHANGE PASSWORD IN PRODUCTION!
INSERT INTO admin_users (email, password_hash, full_name, role)
VALUES ('admin@example.com', '$2b$10$rKzMg8K7xhB8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K8', 'Super Admin', 'super_admin')
ON CONFLICT (email) DO NOTHING;

-- 2.2: Content Library Table (Models & Backgrounds)
-- Supports both admin-uploaded AND user-uploaded content
CREATE TABLE content_library (
  id BIGSERIAL PRIMARY KEY,
  content_type TEXT NOT NULL CHECK (content_type IN ('model', 'background')),
  tier TEXT NOT NULL DEFAULT 'free' CHECK (tier IN ('free', 'premium')),
  category TEXT,
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT NOT NULL,
  storage_path TEXT,
  is_active BOOLEAN DEFAULT true,
  metadata JSONB,
  usage_count INTEGER DEFAULT 0,
  uploaded_by BIGINT REFERENCES admin_users(id),
  owner_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  visibility TEXT DEFAULT 'public' CHECK (visibility IN ('public', 'private')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON COLUMN content_library.owner_user_id IS 'If set, this content belongs to a specific user (premium feature)';
COMMENT ON COLUMN content_library.visibility IS 'public = everyone can see, private = only owner can see';

CREATE INDEX idx_content_library_type ON content_library(content_type);
CREATE INDEX idx_content_library_tier ON content_library(tier);
CREATE INDEX idx_content_library_category ON content_library(category);
CREATE INDEX idx_content_library_active ON content_library(is_active);
CREATE INDEX idx_content_library_owner ON content_library(owner_user_id);
CREATE INDEX idx_content_library_visibility ON content_library(visibility);

-- 2.3: User Limits Table
CREATE TABLE user_limits (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  is_premium BOOLEAN DEFAULT false,
  images_limit INTEGER DEFAULT 10,
  images_used INTEGER DEFAULT 0,
  captions_limit INTEGER DEFAULT 5,
  captions_used INTEGER DEFAULT 0,
  descriptions_limit INTEGER DEFAULT 3,
  descriptions_used INTEGER DEFAULT 0,
  last_reset_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id)
);

CREATE INDEX idx_user_limits_user_id ON user_limits(user_id);
CREATE INDEX idx_user_limits_premium ON user_limits(is_premium);

-- 2.4: Admin Activity Logs Table
CREATE TABLE admin_activity_logs (
  id BIGSERIAL PRIMARY KEY,
  admin_id BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
  action_type TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  description TEXT NOT NULL,
  metadata JSONB,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_admin_logs_admin_id ON admin_activity_logs(admin_id);
CREATE INDEX idx_admin_logs_action_type ON admin_activity_logs(action_type);
CREATE INDEX idx_admin_logs_created_at ON admin_activity_logs(created_at DESC);

-- ========================================
-- Part 3: Row Level Security (RLS)
-- ========================================

-- 3.1: Generated Images RLS
ALTER TABLE generated_images ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view all generations" ON generated_images;
CREATE POLICY "Public can view all generations"
  ON generated_images FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Public can insert generations" ON generated_images;
CREATE POLICY "Public can insert generations"
  ON generated_images FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "Users can update their own generations" ON generated_images;
CREATE POLICY "Users can update their own generations"
  ON generated_images FOR UPDATE TO public
  USING (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own generations" ON generated_images;
CREATE POLICY "Users can delete their own generations"
  ON generated_images FOR DELETE TO public
  USING (user_id IS NULL OR auth.uid() = user_id);

-- 3.2: Admin Tables RLS
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_activity_logs ENABLE ROW LEVEL SECURITY;

-- Admin Users policies
DROP POLICY IF EXISTS "Admins can view admin users" ON admin_users;
CREATE POLICY "Admins can view admin users" ON admin_users FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can update admin users" ON admin_users;
CREATE POLICY "Admins can update admin users" ON admin_users FOR UPDATE USING (true);

-- Content Library policies (supports both admin AND user content)
DROP POLICY IF EXISTS "Users can view public or own content" ON content_library;
CREATE POLICY "Users can view public or own content" ON content_library
  FOR SELECT USING (
    is_active = true AND (
      visibility = 'public'
      OR owner_user_id = auth.uid()
      OR owner_user_id IS NULL
    )
  );

DROP POLICY IF EXISTS "Users can insert their own content" ON content_library;
CREATE POLICY "Users can insert their own content" ON content_library
  FOR INSERT WITH CHECK (
    auth.uid() = owner_user_id OR auth.uid() IS NOT NULL
  );

DROP POLICY IF EXISTS "Users can update their own content" ON content_library;
CREATE POLICY "Users can update their own content" ON content_library
  FOR UPDATE USING (
    owner_user_id = auth.uid() OR owner_user_id IS NULL
  );

DROP POLICY IF EXISTS "Users can delete their own content" ON content_library;
CREATE POLICY "Users can delete their own content" ON content_library
  FOR DELETE USING (
    owner_user_id = auth.uid()
  );

DROP POLICY IF EXISTS "Admins can manage all content" ON content_library;
CREATE POLICY "Admins can manage all content" ON content_library
  FOR ALL USING (true);

-- User Limits policies
DROP POLICY IF EXISTS "Users can view their own limits" ON user_limits;
CREATE POLICY "Users can view their own limits" ON user_limits
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can manage all limits" ON user_limits;
CREATE POLICY "Admins can manage all limits" ON user_limits
  FOR ALL USING (true);

-- Activity Logs policies
DROP POLICY IF EXISTS "Admins can view activity logs" ON admin_activity_logs;
CREATE POLICY "Admins can view activity logs" ON admin_activity_logs
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can insert activity logs" ON admin_activity_logs;
CREATE POLICY "Admins can insert activity logs" ON admin_activity_logs
  FOR INSERT WITH CHECK (true);

-- ========================================
-- Part 4: Storage Buckets
-- ========================================

-- 4.1: Garments Bucket (for user-uploaded garment images)
INSERT INTO storage.buckets (id, name, public)
VALUES ('garments', 'garments', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Garments bucket policies
DROP POLICY IF EXISTS "Public Upload garments" ON storage.objects;
CREATE POLICY "Public Upload garments" ON storage.objects
  FOR INSERT TO public WITH CHECK (bucket_id = 'garments');

DROP POLICY IF EXISTS "Public Download garments" ON storage.objects;
CREATE POLICY "Public Download garments" ON storage.objects
  FOR SELECT TO public USING (bucket_id = 'garments');

DROP POLICY IF EXISTS "Public Update garments" ON storage.objects;
CREATE POLICY "Public Update garments" ON storage.objects
  FOR UPDATE TO public USING (bucket_id = 'garments');

DROP POLICY IF EXISTS "Public Delete garments" ON storage.objects;
CREATE POLICY "Public Delete garments" ON storage.objects
  FOR DELETE TO public USING (bucket_id = 'garments');

-- 4.2: Admin Content Bucket (for admin AND user-uploaded models/backgrounds)
INSERT INTO storage.buckets (id, name, public)
VALUES ('admin-content', 'admin-content', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Admin content bucket policies
DROP POLICY IF EXISTS "Public Upload admin-content" ON storage.objects;
CREATE POLICY "Public Upload admin-content" ON storage.objects
  FOR INSERT TO public WITH CHECK (bucket_id = 'admin-content');

DROP POLICY IF EXISTS "Public Download admin-content" ON storage.objects;
CREATE POLICY "Public Download admin-content" ON storage.objects
  FOR SELECT TO public USING (bucket_id = 'admin-content');

DROP POLICY IF EXISTS "Public Update admin-content" ON storage.objects;
CREATE POLICY "Public Update admin-content" ON storage.objects
  FOR UPDATE TO public USING (bucket_id = 'admin-content');

DROP POLICY IF EXISTS "Public Delete admin-content" ON storage.objects;
CREATE POLICY "Public Delete admin-content" ON storage.objects
  FOR DELETE TO public USING (bucket_id = 'admin-content');

-- ========================================
-- Part 5: Verification & Summary
-- ========================================

-- Show setup summary
SELECT '✅ Database Setup Complete!' as status;

SELECT 'Tables Created:' as info, COUNT(*) as count
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('generated_images', 'admin_users', 'content_library', 'user_limits', 'admin_activity_logs');

SELECT 'Storage Buckets:' as info, COUNT(*) as count
FROM storage.buckets
WHERE id IN ('garments', 'admin-content');

-- Show credentials
SELECT '🔐 Admin Dashboard Credentials:' as info;
SELECT '   Email: admin@example.com' as email;
SELECT '   Password: admin123' as password;
SELECT '   ⚠️  CHANGE PASSWORD IN PRODUCTION!' as warning;

-- Show features
SELECT '📋 Features Enabled:' as features;
SELECT '   ✅ Image generation with AI' as feature1;
SELECT '   ✅ Admin dashboard (/admin)' as feature2;
SELECT '   ✅ User content upload (/my-content.html)' as feature3;
SELECT '   ✅ Premium user support' as feature4;
SELECT '   ✅ Custom models & backgrounds' as feature5;

-- Show next steps
SELECT '🚀 Next Steps:' as next_steps;
SELECT '1. Add SUPABASE_SERVICE_ROLE_KEY to environment' as step1;
SELECT '2. Configure SUPABASE_URL and SUPABASE_ANON_KEY' as step2;
SELECT '3. Create users or sign up through the app' as step3;
SELECT '4. Visit /admin to manage users' as step4;
SELECT '5. Make users premium to allow custom content upload' as step5;
SELECT '6. Premium users can visit /my-content.html to upload' as step6;

-- ========================================
-- Setup Complete!
-- ========================================
